# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a7b57e4f64f2f64c1c4043f526f3a3745d981b28061d8d81b8143d0f4ec98b9e2ce8cbb5b97e8266a4c3c5cca561ada2221ddfcff630c676791b5ea3c1efa5

test:
  secret_key_base: aa6df9d39e044e7ea145e084a9dc4e1625bf976ebd3f6e640b0d0026011c782739a261035da95888d2cb50a4f566dd55ca1bb59245a02cb9f978a45091e10ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
